language: cpp

git:
  depth: 10

matrix:
  include:
    - os: linux
      compiler: gcc
      env: JOBS=10 CXX=g++-4.8
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
    - os: linux
      compiler: clang
      env: JOBS=10 CXX=clang++-3.5
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test','llvm-toolchain-precise-3.5']
          packages: ['clang-3.5']
    - os: osx
      compiler: clang
      env: JOBS=10
      sudo: false

before_install:
 - source ./bootstrap.sh

install:
 - make -j${JOBS}

before_script:
 - make test

script:
 # make sure tileinfo command works
 - ./build/Release/tileinfo examples/data/14_2620_6331.vector.pbf.z