language: c

git:
  depth: 10

sudo: false

matrix:
  include:
    # Broken: https://github.com/mapbox/mapnik-vector-tile/issues/103
    #- os: linux
    #  compiler: gcc
    #  env: JOBS=2 CXX=g++-4.9
    #  addons:
    #    apt:
    #      sources: ['ubuntu-toolchain-r-test']
    #      packages: ['g++-4.9']
    - os: linux
      compiler: clang
      env: JOBS=10 CXX=clang++-3.5
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test','llvm-toolchain-precise-3.5']
          packages: ['clang-3.5']
    - os: osx
      compiler: clang
      env: JOBS=10 BUILDTYPE=Debug
      sudo: false

before_install:
 - source ./bootstrap.sh

install:
 - echo ${CXX}

before_script:
 - make -j${JOBS} test BUILDTYPE=${BUILDTYPE:-Release}

script:
 # make sure tileinfo command works
 - ./build/Release/tileinfo examples/data/14_2620_6331.vector.pbf.z