language: cpp

git:
  depth: 2

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
     - llvm-toolchain-precise-3.5
    packages:
     - clang-3.6

sudo: false

os:
 - osx
 - linux

compiler:
 - clang

before_install:
 - export CXX="clang++-3.6"
 - export CC="clang-3.6"
 - source ./bootstrap.sh

install:
 - make -j10

before_script:
 - make test

script:
 # make sure tileinfo command works
 - ./build/Release/tileinfo examples/data/14_2620_6331.vector.pbf.z