language: cpp

compiler:
 - clang
 - gcc

before_install:
 - sudo apt-add-repository --yes ppa:mapnik/nightly-trunk
 - sudo apt-get update -y

install:
 - sudo apt-get -y install libprotobuf7 libprotobuf-dev protobuf-compiler libmapnik=3.0.0* mapnik-utils=3.0.0* libmapnik-dev=3.0.0* mapnik-input-plugin*=3.0.0* gcc-4.8 g++-4.8

before_script:
 - if [ "${CXX}" = 'g++' ]; then export CXX="g++-4.8" && export CC="gcc-4.8"; fi;

script:
 - make clean
 - make test
 - cd examples/c++
 - make