language: c

git:
  depth: 10

sudo: false

matrix:
  include:
    # Broken: https://github.com/mapbox/mapnik-vector-tile/issues/103
    #- os: linux
    #  compiler: gcc
    #  env: JOBS=2 CXX=g++-4.9
    #  addons:
    #    apt:
    #      sources: ['ubuntu-toolchain-r-test']
    #      packages: ['g++-4.9']
    - os: linux
      compiler: clang
      env: JOBS=10 CXX=clang++-3.5
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test','llvm-toolchain-precise-3.5']
          packages: ['clang-3.5']
    - os: linux
      compiler: clang
      env: JOBS=10 CXX=clang++-3.5 BUILDTYPE=Debug
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test','llvm-toolchain-precise-3.5']
          packages: ['clang-3.5']
    - os: osx
      compiler: clang
      env: JOBS=10 COVERAGE=true BUILDTYPE=Debug
      # https://docs.travis-ci.com/user/languages/objective-c/#Supported-OS-X-iOS-SDK-versions
      osx_image: xcode7.3 # upgrades clang from 6 -> 7
    - os: osx
      compiler: clang
      env: JOBS=10
      # https://docs.travis-ci.com/user/languages/objective-c/#Supported-OS-X-iOS-SDK-versions
      osx_image: xcode7.3 # upgrades clang from 6 -> 7

before_install:
 - source ./bootstrap.sh

install:
 - source ./scripts/build.sh

before_script:
 - ./scripts/coverage.sh

script:
 # make sure tileinfo command works
 - ./build/${BUILDTYPE:-Release}/tileinfo examples/data/14_2620_6331.vector.mvt.z
