language: cpp

sudo: false

os:
 - osx
 - linux

compiler:
 - clang

before_install:
 - source ./bootstrap.sh

install:
 - make test -j10

before_script:
 - true

script:
 - cd examples/c++
 # TODO - incorporate build into main makefile
 #- make