os: Visual Studio 2015

environment:
  msvs_toolset: 14
  matrix:
    - platform: x64
      configuration: Release

shallow_clone: true

install:
  - scripts\build-appveyor.bat

build: off
test: off
deploy: off